#!/usr/bin/env python3
"""Run graphify and write mnemo integration pages."""
from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_IGNORE = [".mnemo/", "graphify-out/", "node_modules/", ".git/", "__pycache__/", "*.pyc", ".venv/", "dist/", "build/", "coverage/", ".next/", ".nuxt/"]


def _created(path: Path) -> str:
    if path.exists():
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("created:"):
                return line.split(":", 1)[1].strip()
    return dt.date.today().isoformat()


def _ensure_ignore(project_root: Path) -> list[str]:
    path = project_root / ".graphifyignore"
    if not path.exists():
        path.write_text("\n".join(DEFAULT_IGNORE) + "\n", encoding="utf-8")
        return DEFAULT_IGNORE
    existing_text = path.read_text(encoding="utf-8")
    existing = {line.strip() for line in existing_text.splitlines() if line.strip()}
    missing = [entry for entry in DEFAULT_IGNORE if entry not in existing]
    if missing:
        path.write_text(existing_text.rstrip("\n") + "\n" + "\n".join(missing) + "\n", encoding="utf-8")
    return missing


def _add_index_links(index: Path) -> None:
    content = index.read_text(encoding="utf-8") if index.exists() else "# Index\n\n## Synthesis\n"
    links = ["- [Codebase Graph Report](wiki/synthesis/codebase-graph-report.md)", "- [Codebase Graph Status](wiki/synthesis/codebase-graph-status.md)"]
    missing = [link for link in links if link not in content]
    if not missing:
        return
    lines = content.splitlines()
    if "## Synthesis" not in lines:
        lines.extend(["", "## Synthesis"])
    insert = lines.index("## Synthesis") + 1
    lines[insert:insert] = missing
    index.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _write_pages(project_root: Path, vault: Path) -> None:
    graph_dir = project_root / "graphify-out"
    report_path = graph_dir / "GRAPH_REPORT.md"
    graph_path = graph_dir / "graph.json"
    if not report_path.exists():
        raise FileNotFoundError("graphify produced no GRAPH_REPORT.md")
    if not graph_path.exists():
        raise FileNotFoundError("graphify produced no graph.json")
    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    if not graph.get("nodes"):
        raise ValueError("graphify produced no nodes")

    today = dt.date.today().isoformat()
    now = dt.datetime.now(dt.timezone.utc).isoformat()
    synthesis = vault / "wiki" / "synthesis"
    synthesis.mkdir(parents=True, exist_ok=True)
    report_page = synthesis / "codebase-graph-report.md"
    status_page = synthesis / "codebase-graph-status.md"
    report = report_path.read_text(encoding="utf-8", errors="replace")
    report_page.write_text(f"""---
title: Codebase Graph Report
category: synthesis
tags: [graphify, codebase, graph-report]
source: graphify-out/GRAPH_REPORT.md
created: {_created(report_page)}
updated: {today}
---

# Codebase Graph Report

> *Generated by graphify on {today}. Canonical runtime artifacts live in `graphify-out/`. Re-run `/mnemo:graphify` to refresh.*

## Canonical Runtime

- Human-readable report: `graphify-out/GRAPH_REPORT.md`
- Structured graph: `graphify-out/graph.json`
- Incremental cache: `graphify-out/cache/`

## Usage

- Read `graphify-out/GRAPH_REPORT.md` first when you need a fast understanding of project structure.
- Use `graphify query ... --graph graphify-out/graph.json` for focused follow-up questions instead of scanning the entire codebase.
- Treat `graphify-out/` as the source of truth for graphify outputs.

## Report

{report}
""", encoding="utf-8")
    status_page.write_text(f"""---
title: Codebase Graph Status
category: synthesis
tags: [graphify, codebase, status]
created: {_created(status_page)}
updated: {today}
---

# Codebase Graph Status

- Canonical runtime directory: `graphify-out/`
- Report present: yes
- Graph present: yes
- Cache present: {"yes" if (graph_dir / "cache").exists() else "no"}
- Last graphify run: {now}

## Guidance

- Start with `graphify-out/GRAPH_REPORT.md`.
- Use `graphify-out/graph.json` for structured queries.
- Leave `graphify-out/cache/` in place so graphify can re-use its SHA256 cache on the next run.
""", encoding="utf-8")
    _add_index_links(vault / "index.md")
    with (vault / "log.md").open("a", encoding="utf-8") as handle:
        handle.write(f"- graphify-out/graph.json | {now} | graphify\n")


def run(project_root: Path, vault: Path, skip_run: bool) -> dict:
    project_root = project_root.resolve()
    vault = vault.resolve()
    if not vault.exists():
        raise FileNotFoundError(f"vault not found: {vault}")
    if not skip_run:
        if shutil.which("graphify") is None:
            raise FileNotFoundError("graphify executable not found")
        _ensure_ignore(project_root)
        result = subprocess.run(["graphify", "."], cwd=project_root)
        if result.returncode != 0:
            raise RuntimeError(f"graphify failed with exit {result.returncode}")
    else:
        _ensure_ignore(project_root)
    _write_pages(project_root, vault)
    return {"status": "mapped", "runtime": str(project_root / "graphify-out"), "vault": str(vault)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run graphify and write mnemo graph pages.")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--vault", required=True)
    parser.add_argument("--skip-run", action="store_true", help="Only validate existing graphify-out artifacts and write pages.")
    args = parser.parse_args(argv)
    try:
        result = run(Path(args.project_root), Path(args.vault), args.skip_run)
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
